services:
  backend:
    build: ./dashboard.api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build: ./dashboard.web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
